FROM node:20-bookworm-slim

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY tsconfig*.json vite.config.ts ./

EXPOSE 5173

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]
